shared:
    image: node:8
jobs:
    SIMPLE:
        steps:
            - echo: echo test
        requires: [~pr, ~commit]
    PARALLEL1:
        steps:
            - echo: echo test
        requires: [SIMPLE]
    PARALLEL2:
        steps:
            - echo: echo test
        requires: [SIMPLE]
    JOIN:
        steps:
            - echo: echo test
        requires: [PARALLEL1, PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
    AFTER-FAIL:
        steps:
            - echo: echo test
        requires: [FAIL]
    STAGING:
        steps:
            - echo: echo test
        requires: [~pr:staging, ~commit:staging]
    AFTER-STAGING:
        steps:
            - echo: echo test
        requires: [STAGING]
    REGEX:
        steps:
            - echo: echo test
        requires: [~pr:/^.*$/, ~commit:/^.*$/]
    UNMATCH-REGEX:
        steps:
            - echo: echo test
        requires: [~pr:/^unmatch$/, ~commit:/^unmatch$/]
    MASTER-PR:
        steps:
            - echo: echo test
        requires: [~pr:master]
    AFTER-MASTER-PR:
        steps:
            - echo: echo test
        requires: [MASTER-PR]
