shared:
    image: node:20
    steps:
        - echo: echo test
    annotations:
        screwdriver.cd/virtualJob: true
jobs:
    SIMPLE:
        requires: [~pr, ~commit]
    PARALLEL1:
        requires: [SIMPLE]
    PARALLEL2:
        requires: [SIMPLE]
    JOIN:
        requires: [PARALLEL1, PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
        annotations:
            screwdriver.cd/virtualJob: false
    AFTER-FAIL:
        requires: [FAIL]
    AFTER-FAIL-JOIN:
        requires: [SIMPLE, FAIL]
    STAGING:
        requires: [~pr:staging, ~commit:staging]
    AFTER-STAGING:
        requires: [STAGING]
    REGEX:
        requires: [~pr:/^.*$/, ~commit:/^.*$/]
    MASTER-PR:
        requires: [~pr:master]
    AFTER-MASTER-PR:
        requires: [MASTER-PR]
